myapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='myapp'
urlpatterns = [
    path('',views.index,name='home'),
    path('contact/',views.contact,name='contact'),
    path('products/',views.products,name='products'),
    path('products/<int:pk>/',views.ProductDetailView.as_view(), name='product_detail'),
    path('products/add/',views.add_product,name='add_product'),
    path('products/update/<int:pk>',views.ProductUpdateView.as_view(),name='update_product'),
    path('products/delete/<int:pk>',views.ProductDelete.as_view(),name='delete_product'),
    path('products/mylistings',views.my_listings,name='mylistings'),
    path('success/',views.PaymentSuccessView.as_view(),name='success'),
    path('failed/',views.PaymentFailedView.as_view(),name='failed'),
    path('api/checkout-session/<id>',views.create_checkout_session,name='api_checkout_session')
]

mysite/urls.py
# from types import _StaticFunctionType
from django.contrib import admin
# from django.urls import path
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static 
# from mysite.mysite.settings import STATIC_URL
urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')),
    path('users/',include('users.urls')),
]

urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from re import template
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views
app_name='users'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',views.profile,name='profile'),
    path('createprofile/',views.create_profile,name='create_profile'),
    path('sellerprofile/<int:id>/',views.seller_profile,name='sellerprofile'),
]

users/models.py
from distutils.command.upload import upload
from email.policy import default
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Profile(models.Model):
    def __str__(self):
        return self.user.username
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image=models.ImageField(default='profile.jpg',upload_to='profile_pictures')
    contact_number = models.CharField(max_length=100,default="9082195422")

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class':'focus:outline-none','placeholder':'Enter your Email ID'}))
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'focus:outline-none','placeholder':'Enter your username'}))
    password1 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class':'focus:outline-none','placeholder':'Enter your password'}))
    password2 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class':'focus:outline-none','placeholder':'Enter confirm password'}))

    class Meta:
        model=User
        fields=("username","email","password1","password2")
    
    def save(self,commit=True):
        user = super(NewUserForm,self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

users/views.py
from django.shortcuts import redirect, render
from .forms import NewUserForm
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib.auth.models import User
# Create your views here.
def register(request):
    if request.method=='POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('/myapp/products/')

    form = NewUserForm()
    context={
        'form':form,
    }
    return render(request,'users/register.html',context)

@login_required
def profile(request):
    return render(request,'users/profile.html')

def create_profile(request):
    if request.method =='POST':
        contact_number = request.POST.get('contact_number')
        image = request.FILES['upload']
        user = request.user
        profile = Profile(user=user,image=image,contact_number=contact_number)
        profile.save()
    return render(request,'users/createprofile.html')

def seller_profile(request,id):
    seller = User.objects.get(id=id)
    context = {
        'seller':seller,
    }
    return render(request, 'users/sellerprofile.html',context)

users/templates/users/createprofile.html
{% extends 'myapp/base.html' %}
{% block content %}
{% load static %}
<div class="text-2xl ml-10 p-10 font-bold">🧑Create Profile
    <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0 font-semibold">
        Newly registered user can add their photo and contact number here only for the first time. For updating profile, already registered users have to contact admin.
    </p>
</div>
<form method="post" enctype="multipart/form-data" class="flex bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4">
    {% csrf_token %}
    <div>
        <img class="mt-3 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0" src="{% static 'myapp/images/profile.jpg' %}" alt='job hunt' style='width: 100%;' />
    </div>
    <div>
        <div class="mb-4">
            <label for="">Upload profile image</label>
            <input class="py-2" placeholder="Upload a clear profile image" type="file" accept="image/*" name="upload" id="upload">
         </div>
         <div class="mb-4">
             <label for="">Contact Number : </label>
             <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="Enter your contact number" type="text"  name="contact_number" id="contact_number">
         </div>
         <input type="submit" class="bg-green-500 hover:bg-green-700 text-white px-5 py-2" name="Add" value="Add">
    </div>
</form>
{% endblock %}

users/templates/users/login.html
{% extends 'myapp/base.html' %}
{% block content %}
{% load static %}
<h1 class="text-2xl m-10 font-bold">🧑 Login User</h1>
<main class="mt-2 mx-auto max-w-7xl px-4 sm:mt-2 sm:px-6 md:mt-2 lg:mt-2 lg:px-8 xl:mt-2 ">
    <span class="flex">
        <span>
            <img class="mt-3 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0" src="{% static 'myapp/images/login.jpg' %}" alt='job hunt' style='width: 100%;' />
        </span>
        <span class="container py-5">
            <div>
                <form method="post" class="w-3/5 bg-white shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4">
                    {% csrf_token %}
                    <div class="mb-2">
                        <label for="">Username :</label>
                        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                            {{form.username}}
                        </div>
                    </div>
                    <div class="mb-2">
                        <label for="">Password :</label>
                        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                            {{form.password}}
                        </div>
                    </div>
                    <button type="submit" class="bg-green-500 hover:bg-green-700 text-white px-5 py-2">Login</button>
                </form>
                <div class="m-10">Do not have an account ?
                    <a class="text-indigo-500" href="{% url 'users:register' %}">Register</a>
                </div>
            </div>
        </span>
    </span>
 </main>
{% endblock %}

users/templates/users/logout.html
{% extends 'myapp/base.html' %}
{% block content %}
{% load static %}
<Wrapper>
    <main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-24 ">
        <span>
            <div class="sm:text-center lg:text-left">
                <h1 class="text-4xl font-extrabold text-gray-900 sm:text-4xl md:text-5xl">
                    <span class="block xl:inline">Logged</span>
                    <span class="block text-green-500 xl:inline"> Out</span>
                </h1>
                <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">You've been logged out successfully.</p>
                <span>
                    <img class="mt-3 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 ml-130 md:text-xl lg:mr-20" src="{% static 'myapp/images/logout.jpg' %}" alt='job hunt' style='width: 100%;' />
                </span>
        </span>
     </main>
</Wrapper>
{% endblock %}

users/templates/users/profile.html
{% extends 'myapp/base.html' %}
{% block content %}
{% load static %}
<div class="text-2xl ml-10 p-10 font-bold">🧑My Profile</div>
<div class="grid p-20 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="mr-20">
        <img class="mt-3 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 ml-130 md:text-xl lg:mr-20" src="{% static 'myapp/images/userprofile.jpg' %}" alt='job hunt' style='width: 100%;' />
    </div>
    <div class="rounded shadow-lg mr-20">
        <div>
            <img class=""src="{{user.profile.image.url}}" alt="">
        </div>
        <div class="font-semibold text-xl mb-2 px-6 py-4">
            <h1>Username : {{user.username}}</h1>
        </div>
        <div class="font-semibold text-xl mb-2 px-6 py-4">
            <h1>Email : {{user.email}}</h1>
        </div>
        <div class="font-semibold text-xl mb-2 px-6 py-4">
            <h1>📞 Contact Number : {{user.profile.contact_number}}</h1>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'myapp/base.html' %}
{% block content %}
{% load static %}
<h1 class="text-2xl m-10 font-bold">🧑 Register User</h1>
<main class="mt-2 mx-auto max-w-7xl px-4 sm:mt-2 sm:px-6 md:mt-2 lg:mt-2 lg:px-8 xl:mt-2">
    <span class="flex">
        <span>
            <img class="mt-3 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0" src="{% static 'myapp/images/registration.jpg' %}" alt='job hunt' style='width: 100%;' />
        </span>
        <span class="container py-5">
            <div>
                <form method="post" class="w-3/5 bg-white shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4">
                    {% csrf_token %}
                    <div class="mb-2">
                        <label for="">Username :</label>
                        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                            {{form.username}}
                        </div>
                    </div>
                    <div class="mb-2">
                        <label for="">Email :</label>
                        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                            {{form.email}}
                        </div>
                    </div>
                    <div class="mb-2">
                        <label for="">Password :</label>
                        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                            {{form.password1}}
                        </div>
                    </div>
                    <div class="mb-2">
                        <label for="">Confirm Password :</label>
                        <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                            {{form.password2}}
                        </div>
                    </div>
                    <button type="submit" class="bg-green-500 hover:bg-green-700 text-white px-5 py-2">Register</button>
                </form>
                <div class="m-10">Are you already registered?
                    <a class="text-indigo-500" href="{% url 'users:login' %}">Login</a>
                </div>
            </div>
        </span>
    </span>
 </main>
{% endblock %}

users/templates/users/sellerprofile.html
{% extends 'myapp/base.html' %}
{% block content %}
{% load static %}
<div class="grid p-20 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="mr-20">
        <img class="mt-3 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 ml-130 md:text-xl lg:mr-20" src="{% static 'myapp/images/userprofile.jpg' %}" alt='job hunt' style='width: 100%;' />
    </div>
    <div class="rounded shadow-lg">
        <div>
            <img class=""src="{{seller.profile.image.url}}" alt="">
        </div>
        <div class="font-semibold text-xl mb-2 px-6 py-4">
            <h1>Username : {{seller.username}}</h1>
        </div>
        <div class="font-semibold text-xl mb-2 px-6 py-4">
            <h1>Email : {{seller.email}}</h1>
        </div>
        <div class="font-semibold text-xl mb-2 px-6 py-4">
            <h1>📞 Contact Number : {{seller.profile.contact_number}}</h1>
        </div>
    </div>
</div>
{% endblock %}