myapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='myapp'
urlpatterns = [
    path('',views.index,name='home'),
    path('contact/',views.contact,name='contact'),
    path('products/',views.products,name='products'),
    path('products/<int:pk>/',views.ProductDetailView.as_view(), name='product_detail'),
    path('products/add/',views.add_product,name='add_product'),
    path('products/update/<int:pk>',views.ProductUpdateView.as_view(),name='update_product'),
    path('products/delete/<int:pk>',views.ProductDelete.as_view(),name='delete_product'),
    path('products/mylistings',views.my_listings,name='mylistings'),
    path('success/',views.PaymentSuccessView.as_view(),name='success'),
    path('failed/',views.PaymentFailedView.as_view(),name='failed'),
    path('api/checkout-session/<id>',views.create_checkout_session,name='api_checkout_session')
]

mysite/urls.py
# from types import _StaticFunctionType
from django.contrib import admin
# from django.urls import path
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static 
# from mysite.mysite.settings import STATIC_URL
urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')),
    path('users/',include('users.urls')),
]

urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from re import template
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views
app_name='users'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',views.profile,name='profile'),
    path('createprofile/',views.create_profile,name='create_profile'),
    path('sellerprofile/<int:id>/',views.seller_profile,name='sellerprofile'),
]

myapp/models.py
from django.urls import reverse
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Product(models.Model):
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('myapp:products')
    
    seller_name = models.ForeignKey(User, on_delete=models.CASCADE,default=1)
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    desc = models.CharField(max_length=200)
    image = models.ImageField(blank=True, upload_to="images")
    
class OrderDetail(models.Model):
    customer_username = models.CharField(max_length=200)
    product = models.ForeignKey(to='Product',on_delete=models.PROTECT)
    amount = models.IntegerField()
    stripe_payment_intent = models.CharField(max_length=200)
    has_paid = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True) 
    updated_on = models.DateTimeField(auto_now_add=True)

myapp/views.py
from math import prod
from django.conf import settings
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.urls import reverse_lazy
from requests import session
from .models import Product,OrderDetail
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView,DetailView,TemplateView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.paginator import Paginator
from django.http.response import HttpResponseNotFound, JsonResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
import json
import stripe
# Create your views here.
def index(request):
    return render(request,'myapp/home.html')

def contact(request):
    return render(request,'myapp/contact.html')

def products(request):
    page_obj = products = Product.objects.all()
    product_name = request.GET.get('product_name')
    if product_name!='' and product_name is not None:
        page_obj = products.filter(name__icontains=product_name)
    paginator = Paginator(page_obj,3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj':page_obj
    }
    return render(request,'myapp/index.html',context)

# CLass based view for above products view (ListView)
class ProductListView(ListView):
    model = Product
    template_name = 'myapp/index.html'
    context_object_name = 'products'
    paginate_by = 3

def product_detail(request,id):
    product = Product.objects.get(id=id)
    context = {
        'product':product
    }
    return render(request,'myapp/details.html',context)

# CLass based view for above product detail view (ListView)
class ProductDetailView(DetailView):
      model = Product
      template_name = 'myapp/details.html'
      context_object_name = 'product'
      pk_url_kwarg = 'pk'

      def get_context_data(self,**kwargs):
          context = super(ProductDetailView,self).get_context_data(**kwargs)
          context['stripe_publishable_key'] = settings.STRIPE_PUBLISHABLE_KEY
          return context

@login_required
def add_product(request):
    if request.method=='POST':
       name = request.POST.get('name')
       price = request.POST.get('price')
       desc = request.POST.get('desc')
       image = request.FILES['upload']
       seller_name = request.user
       product = Product(name=name,price=price,desc=desc,image=image,seller_name=seller_name)
       product.save()
       return redirect('/myapp/products/')
    return render(request,'myapp/addproduct.html')

# CLass based view for creating a product
# @login_required
class ProductCreateView(CreateView):
    model = Product
    fields = ['name', 'price', 'desc', 'image', 'seller_name']
    # 'product_form.html'

def update_product(request,id):
    product = Product.objects.get(id=id)
    if request.method=='POST':
        product.name = request.POST.get('name')
        product.price = request.POST.get('price')
        product.desc = request.POST.get('desc')
        product.image = request.FILES['upload']
        product.save()
        return redirect('/myapp/products/')
    context = {
        'product':product,
    }
    return render(request,'myapp/updateproduct.html',context)

# CLass based view for updating a product
class ProductUpdateView(UpdateView):
    model = Product
    fields = ['name', 'price', 'desc', 'image', 'seller_name']
    template_name_suffix = '_update_form'

def delete_product(request,id):
    product = Product.objects.get(id=id)
    context = {
        'product':product,
    }
    if request.method=='POST':
        product.delete()
        return redirect('/myapp/products/')
    return render(request,'myapp/delete.html',context)
# Class based Delete View
class ProductDelete(DeleteView):
    model = Product
    success_url = reverse_lazy('myapp:products')
    context_object_name = 'product'
    template_name_suffix = '_confirm_delete'
def my_listings(request):
    products = Product.objects.filter(seller_name=request.user)
    context={
        'products':products,
    }
    return render(request,'myapp/mylistings.html',context)

@csrf_exempt
def create_checkout_session(request,id):
    products = Product.objects.exclude(seller_name=request.user)
    product = get_object_or_404(products, pk=id)
    stripe.api_key = settings.STRIPE_SECRET_KEY
    checkout_session = stripe.checkout.Session.create(
        customer_email = request.user.email,
        payment_method_types=['card'],
        line_items=[
            {
                'price_data':{
                    'currency':'usd',
                    'product_data':{
                        'name':product.name,
                    },
                    'unit_amount':int(product.price*100),
                },
                'quantity':1,
            }
        ],    
            mode='payment',
            success_url = request.build_absolute_uri(reverse('myapp:success'))+"?session_id={CHECKOUT_SESSION_ID}",
            cancel_url = request.build_absolute_uri(reverse('myapp:failed')),
    )

    order=OrderDetail()
    order.customer_username = request.user.username
    order.product = product
    order.stripe_payment_intent = checkout_session['payment_intent']
    order.amount = int(product.price*100)
    order.save()
    return JsonResponse({'sessionId':checkout_session.id})

class PaymentSuccessView(TemplateView):
    template_name = 'myapp/payment_success.html'
    
    def get(self,request,*args,**kwargs):
        session_id = request.GET.get('session_id')
        if session_id is None:
            return HttpResponseNotFound()
        session = stripe.checkout.Session.retrieve(session_id)
        stripe.api_key = settings.STRIPE_SECRET_KEY
        order = get_object_or_404(OrderDetail,stripe_payment_intent=session.payment_intent)
        order.has_paid = True
        order.save()
        return render(request,self.template_name)

class PaymentFailedView(TemplateView):
    template_name = 'myapp/payment_failed.html'

myapp/templates/myapp/addproduct.html
{% extends 'myapp/base.html'%}
{% block content %}
{% load static %}
<h1 class="text-2xl font-bold m-10">➕Add Product</h1>
<form class="flex w-3/5 bg-white shadow-md m-10 px-8 py-8" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
  <div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Name :</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="Enter Product Name" type="text" name="name" id="name">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Price :</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="Enter Product Price" type="text" name="price" id="price">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Description :</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="Enter Product Description" type="text" name="desc" id="desc">
    </div>
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="">Product Image :</label>
        <input class="py-2" type="file" accept="image/*" name="upload" id="upload">
    </div>
    <!-- <input placeholder="price" type="text" name="price" id="price">
    <input placeholder="desc" type="text" name="desc" id="desc"> -->
    <!-- <input type="file" accept="image/*" name="upload" id="upload"> -->
    <div class="mb-4">
      <input class="bg-green-500 hover:bg-green-700 text-white px-5 py-2" type="submit" name="Add Product" value="Add Product" id=""> 
    </div>
  </div>
  <div>
    <img class="mt-3 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0" src="{% static 'myapp/images/add.jpg' %}" alt='job hunt' style='width: 100%;' />
  </div> 
    <!-- <input type="submit" name="Add Product" value="Add Product" id=""> -->
</form>
{% endblock %}

myapp/templates/myapp/base.html
{% load static %}
<html>
    <head>
    <link rel="icon" href="{% static 'myapp/images/shopping.png' %}" />
    <title>Buy and Sell Website</title>
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}" />
    <style>
        .active{
            border-bottom-width: 4px;
            --tw-border-opacity: 1;
            border-color: rgba(16, 185, 129, var(--tw-border-opacity));
        }
    </style>
  </head>
  <body>
    <nav class="bg-white shadow-lg">
      <div class="max-w-6xl mx-auto px-4">
        <div class="flex justify-between">
          <div class="flex space-x-7">
            <div>
              <a href="{% url 'myapp:home' %}" class="flex items-center px-2 py-4">
                <img
                  class="h-8 w-8"
                  src="{% static 'myapp/images/shopping.png' %}"
                  alt=""
                />
                <span class="text-gray-500 font-semibold text-lg"
                  >Buy&Sell</span
                >
              </a>
            </div>
            <div class="items-center flex space-x-1">
              <a
                href="{% url 'myapp:home' %}"
                class="py-4 px-2 text-gray-500 font-semibold ac"
                >Home</a
              >
              <a
                href="{% url 'myapp:add_product' %}"
                class="py-4 px-2 text-gray-500 font-semibold ac"
                >Post Ad</a
              >
              <a
                href="{% url 'myapp:products' %}"
                class="py-4 px-2 text-gray-500 font-semibold ac"
                >View Products</a
              >
              <a
                href="{% url 'myapp:contact' %}"
                class="py-4 px-2 text-gray-500 font-semibold ac"
                >Contact</a
              >
              {% if user.is_authenticated %}
              <a
                href="{% url 'users:logout'%}"
                class="py-4 px-10 text-gray-500 font-semibold ac"
                >Logout</a
              >
              <a
                href="{% url 'users:profile'%}"
                class="py-4 px-10 text-gray-500 font-semibold ac"
                >Profile</a
              >
              <a
                href="{% url 'users:create_profile' %}"
                class="py-4 px-10 text-gray-500 font-semibold ac"
                >Create Profile</a
              >
              <a
                href="{% url 'myapp:mylistings' %}"
                class="py-4 px-10 text-gray-500 font-semibold ac"
                >My Listings</a
              >
              {% else %}
              <a
                href="{% url 'users:login'%}"
                class="py-4 px-10 text-gray-500 font-semibold ac"
                >Login</a
              >
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </nav>
    {% block content %} 

    {% endblock %}
  </body>
  <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script>
    $(function () {
      $(".ac").each(function () {
        if ($(this).prop("href") == window.location.href) {
          $(this).addClass("active");
        }
      });
    });
  </script>
</html>

myapp/templates/myapp/contact.html
{% extends 'myapp/base.html' %}
{% block content %}
{% load static %}
<Wrapper>
    <main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-24 inline flex">
        <span>
            <img class="mt-3 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 ml-130 md:text-xl lg:mr-20" src="{% static 'myapp/images/contact.jpg' %}" alt='job hunt' style='width: 100%;' />
        </span>
        <span>
            <div class="sm:text-center lg:text-left">
                <h1 class="text-4xl font-extrabold text-gray-900 sm:text-4xl md:text-5xl">
                    <span class="block xl:inline">Contact</span>
                    <span class="block text-green-500 xl:inline">Us</span>
                </h1>
                <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">
                    You can reach us out at :<br/><br/>
                    📧 adityaganji889@gmail.com,adityaganji89@gmail.com<br/><br/>
                    📞 +91-9082195422,9653124526,8369232660<br/><br/>
                   <a href="https://www.instagram.com/adityaganji889/" target=_blank class="inline flex">
                    <img
                    class="h-8 w-8 mr-5"
                    src="{% static 'myapp/images/instagram.png' %}"
                    alt=""
                     /> 
                     <span class="hover:text-gray-900">Instagram</span>
                  </a><br/>
                  <a href="https://www.linkedin.com/in/aditya-ganji-40725b1b2/" target=_blank class="inline flex">
                    <img
                    class="h-8 w-8 mr-5"
                    src="{% static 'myapp/images/linkedin.png' %}"
                    alt=""
                     /> 
                     <span class="hover:text-gray-900">Linkedin</span>
                  </a><br/>
                  <a href="https://github.com/adityaganji889" target=_blank class="inline flex">
                    <img
                    class="h-8 w-8 mr-5"
                    src="{% static 'myapp/images/github.png' %}"
                    alt=""
                     /> 
                     <span class="hover:text-gray-900">Github</span>
                  </a><br/>
                  
                </p>
            </div>
        </span>
        
     </main>
</Wrapper>
{% endblock %}

myapp/templates/myapp/delete.html
{% extends 'myapp/base.html' %}
{% block content %}
{% load static %}
<h1 class="text-2xl m-10 font-bold">Delete Product</h1>
<form method="POST" class="flex bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4">
   {% csrf_token %}
   <div>
    <img class="mt-3 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0" src="{% static 'myapp/images/delete.jpg' %}" alt='job hunt' style='width: 100%;' />
   </div>
   <div>
     <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2">Are you sure you want to delete this product ?</label>
     </div>
     <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2">
            {{product.name}}
        </label>
     </div>
     <div class="mb-4">
        <img class="h-40 w-40"src="{{product.image.url}}" alt="">
     </div>
        <input type="submit" class="bg-red-500 text-white px-5 py-2" name="confirm" value="Confirm" >
        <a class="button bg-green-500 text-white px-5 py-3" href="{% url 'myapp:products' %}">Cancel</a>
   </div>
  </div>
   <!-- <input type="submit" class="bg-red-500 text-white px-5 py-2" name="confirm" value="Confirm" >
   <a class="bg-red-500 text-white px-5 py-2" href="{% url 'myapp:products' %}">Cancel</a> -->
</form>
{% endblock %}

myapp/templates/myapp/details.html
{% extends 'myapp/base.html' %}
{% block content %}
{% load static %}
<!-- This is a detailed page for :  -->
<div class="text-2xl ml-10 p-10 font-bold">📄Product Details</div>
<div class="flex p-10 w-full h-200">
    <img class="w-1/3" src="{{product.image.url}}" alt="">
    <div class="w-1/3 text-xl ml-10 mt-10">
        <div class="mt-5">{{product.name}} </div>
        <div class="mt-5 text-green-500">${{product.price}}</div>
        <div class="mt-5 text-gray-700">{{product.desc}}</div>
        <div class="mt-5 text-gray-700">
            Posted by : 
            <a href="{% url 'users:sellerprofile' product.seller_name.id %}" class="hover:text-green-500">
                {{product.seller_name}}
            </a>
        </div>
        <div class="mt-5 text-gray-700">📞 {{product.seller_name.profile.contact_number}}</div>
        <div>
            <button class="bg-green-500 hover:bg-green-700 text-white px-3 py-2 mt-5" id="Checkout">Checkout</button>
            <button class="bg-blue-500 hover:bg-blue-700 text-white px-3 py-2 mt-5" id="Checkout"><a href="{% url 'users:sellerprofile' product.seller_name.id %}" class="hover:text-green-500">View Seller Details</a></button>
        </div>
    </div>
    <img class="w-1/3" src="{% static 'myapp/images/product.jpg' %}" alt="" width="50%">
    <script src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript">
        var stripe = Stripe('{{ stripe_publishable_key }}')
        var CheckoutButton = document.getElementById('Checkout')
        CheckoutButton.addEventListener('click',function(){
            fetch("{% url 'myapp:api_checkout_session' id=product.id %}",{method:'POST'})
            .then(function(response){
             return response.json()  
          })
          .then(function(session){
            return stripe.redirectToCheckout({sessionId:session.sessionId})
          })
          .then(function(result){
            if(result.error){
                alert(result.error.message)
            }
          })
          .catch(function(error){
            console.log('Error',error)
          })
        })
    </script>
</div>
{% endblock %}
    

myapp/templates/myapp/home.html
{% extends 'myapp/base.html' %}
{% block content %}
{% load static %}
<Wrapper>
    <main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-24 ">
        <span>
            <div class="sm:text-center lg:text-left">
                <h1 class="text-4xl font-extrabold text-gray-900 sm:text-4xl md:text-5xl">
                    <span class="block xl:inline">Buy &</span>
                    <span class="block text-green-500 xl:inline"> Sell Website</span>
                </h1>
                <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">One of the world's biggest free online classified! Its a unique platform for people to buy or sell items from an array of products & services like cars, electronics, real estate,jobs & more!</p>
                <span>
                    <img class="mt-3 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 ml-130 md:text-xl lg:mr-20" src="{% static 'myapp/images/shop.jpg' %}" alt='job hunt' style='width: 100%;' />
                </span>
            </div>
        </span>
     </main>
</Wrapper>
{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block content %}
     <!-- <h1>
        This is a template. This is being rendered.
     </h1>    -->
     <!-- Site Hero starts here -->
     <main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
        <div class="sm:text-center lg:text-left">
            <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
                <span class="block xl:inline">Premium Products</span>
                <span class="block text-green-500 xl:inline">Non-Premium Prices</span>
            </h1>
            <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Get the best quality used products across the globe. Free shipping</p>
        </div>
     </main>
      <!-- Site Hero ends here -->
     <div class="flex mt-5 p-10 justify-center">
        <h2 class="text-3xl font-normal mt-0 mb-0 text-gray-500">Recent Products</h2>
     </div>
     <div class="flex mt-5 p-10 justify-center">
       <!-- <h2 class="text-3xl font-normal mt-0 mb-2 text-gray-500">Search Products</h2> -->
       <form method="GET">
        <input class="shadow-lg border rounded py-5 px-40 mx-10 text-gray-700 border-blue-500" type="text" name="product_name" id="product_name" placeholder="Type a product to search">
       </form>
     </div>
     <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-cols-3 lg:grid-cols-3 gap-5">
       <!-- Card 1 -->
       {% for product in page_obj %}
       <a href="{% url 'myapp:product_detail' product.id %}">
        <div class="rounded overflow-hidden shadow-lg">
            <img class = "w-full" src="{{product.image.url}}" alt="">
            <div class="px-6 py-4">
                <div class="font-bold text-xl mb-2">{{product.name}}</div>
                <div class="font-bold text-xl text-green-500 mb-2">${{product.price}}</div>
                <div class="font-bold mb-2">Posted by : <span class="text-purple-500">{{product.seller_name}}</span></div>
                <p class="text-gray-700 text-base">{{product.desc}}</p>
            </div>
        </div>
       </a>
       {% endfor %}
     </div>
     <!-- pagination code starts here -->
     <div class="pagination flex mt-5 p-10 justify-center items-center">
         <span>
            {% if page_obj.has_previous %}
               <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10" href="?page=1">First</a>
               <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10" href="?page={{page_obj.previous_page_number}}">Previous</a>
            {% endif %}
            <span class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10">
                Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
            </span>
            {% if page_obj.has_next %}
               <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10" href="?page={{page_obj.next_page_number}}">Next</a>
               <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10" href="?page={{page_obj.paginator.num_pages}}">Last</a>
            {% endif %}
         </span>
     </div>
     <!-- pagination code ends here -->
{% endblock %}

myapp/templates/myapp/mylistings.html
{% extends 'myapp/base.html' %}
{% block content %}
<div class="text-2xl m-10 p-10 font-bold">📜My Listings</div>
{% for product in products %}
<div class="itemcontainer flex shadow-lg m-10 p-10">
    <span class="w-1/5">
        <img class="w-40 h-40" src="{{product.image.url}}" alt="">
    </span>
    <span class="w-2/5">
        <div class="font-bold text-gray-700">{{product.name}}</div>
        <div class="text-green-500">$ {{product.price}}</div>
        <div>{{product.desc}}</div>
    </span>
    <span class="w-1/5 my-10 mx-10">
        <a class="bg-green-500 text-white font-bold px-5 py-2" href="{% url 'myapp:update_product' product.id %}">📝Edit</a>
    </span>
    <span class="w-1/5 my-10 mx-10">
        <a class="bg-red-500 text-white font-bold px-5 py-2" href="{% url 'myapp:delete_product' product.id %}">🗑️Delete</a>
    </span>
</div>
{% endfor %}
{% endblock %}

myapp/templates/myapp/payment_failed.html
{% extends 'myapp/base.html' %}
{% block content %}
{% load static %}
<Wrapper>
    <main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-24 ">
        <span>
            <div class="sm:text-center lg:text-left">
                <h1 class="text-4xl font-extrabold text-gray-900 sm:text-4xl md:text-5xl">
                    <span class="block xl:inline">Payment</span>
                    <span class="block text-red-500 xl:inline">Failed</span>
                </h1>
                <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">We're unable to receive your order, payment got failed.</p>
                <span>
                    <img class="mt-3 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 ml-130 md:text-xl lg:mr-20" src="{% static 'myapp/images/paymentfailure.jpg' %}" alt='job hunt' style='width: 100%;' />
                </span>
        </span>
     </main>
</Wrapper>
{% endblock %}

myapp/templates/myapp/payment_success.html
{% extends 'myapp/base.html' %}
{% block content %}
{% load static %}
<Wrapper>
    <main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-24 ">
        <span>
            <div class="sm:text-center lg:text-left">
                <h1 class="text-4xl font-extrabold text-gray-900 sm:text-4xl md:text-5xl">
                    <span class="block xl:inline">Payment</span>
                    <span class="block text-green-500 xl:inline">Successful</span>
                </h1>
                <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">We received your order, payment was successful.</p>
                <span>
                    <img class="mt-3 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 ml-130 md:text-xl lg:mr-20" src="{% static 'myapp/images/paymentsuccess.jpg' %}" alt='job hunt' style='width: 100%;' />
                </span>
        </span>
     </main>
</Wrapper>
{% endblock %}